name: ai-upscaler
channels:
  - defaults
  - pytorch
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - numpy=1.24.4
  - opencv
  - pillow
  - flask
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pip:
      - basicsr
      - realesrgan
